"""multi_tenancy

Revision ID: fa5d990d2561
Revises: b8edb27a6806
Create Date: 2026-08-11 08:25:15.676043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5d990d2561'
down_revision: Union[str, Sequence[str], None] = 'b8edb27a6806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


import uuid

def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create organizations table
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    
    # 2. Insert Default Organization
    default_org_id = uuid.uuid4()
    op.execute(f"INSERT INTO organizations (id, name, created_at) VALUES ('{default_org_id}', 'Default Organization', NOW())")

    # 3. Add organization_id columns as NULLABLE first
    op.add_column('istasyonlar', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.add_column('kullanicilar', sa.Column('organization_id', sa.Uuid(), nullable=True))

    # 4. Backfill existing records with the default organization id
    op.execute(f"UPDATE istasyonlar SET organization_id = '{default_org_id}'")
    op.execute(f"UPDATE kullanicilar SET organization_id = '{default_org_id}'")

    # 5. Alter columns to be NOT NULL
    op.alter_column('istasyonlar', 'organization_id', nullable=False)
    op.alter_column('kullanicilar', 'organization_id', nullable=False)

    # 6. Create Foreign Keys
    op.create_foreign_key('fk_istasyonlar_org', 'istasyonlar', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('fk_kullanicilar_org', 'kullanicilar', 'organizations', ['organization_id'], ['id'])



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_kullanicilar_org', 'kullanicilar', type_='foreignkey')
    op.drop_column('kullanicilar', 'organization_id')
    op.drop_constraint('fk_istasyonlar_org', 'istasyonlar', type_='foreignkey')
    op.drop_column('istasyonlar', 'organization_id')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
